# Generated by Django 5.1 on 2024-12-05 20:46

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quality_factor', models.IntegerField(default=85)),
                ('max_dimensions', models.IntegerField(default=2000)),
                ('webp_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('original_image', imagekit.models.fields.ProcessedImageField(upload_to='original_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('optimized_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='optimized_images/%Y/%m/%d/')),
                ('original_size', models.IntegerField(default=0)),
                ('compressed_size', models.IntegerField(default=0)),
                ('compression_ratio', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compression_strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.compressionstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_time_original', models.FloatField()),
                ('load_time_optimized', models.FloatField()),
                ('bandwidth_saved', models.IntegerField()),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.optimizedimage')),
            ],
        ),
    ]
