# Generated by Django 5.1 on 2024-12-06 23:14

import django.core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_remove_compressionstrategy_webp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedimage',
            name='original_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='original_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])]),
        ),
    ]
