# Generated by Django 5.1 on 2024-12-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_alter_optimizedimage_original_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetric',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Métrique de Performance', 'verbose_name_plural': 'Métriques de Performance'},
        ),
        migrations.AddField(
            model_name='compressionstrategy',
            name='cache_control',
            field=models.CharField(default='public, max-age=31536000', help_text='Directives de mise en cache du navigateur', max_length=100),
        ),
        migrations.AddField(
            model_name='compressionstrategy',
            name='enable_lazy_loading',
            field=models.BooleanField(default=True, help_text='Activer le chargement différé'),
        ),
        migrations.AddField(
            model_name='compressionstrategy',
            name='generate_responsive',
            field=models.BooleanField(default=True, help_text='Générer des versions responsives'),
        ),
        migrations.AddField(
            model_name='compressionstrategy',
            name='resize_strategy',
            field=models.CharField(choices=[('fit', 'Ajuster aux Dimensions'), ('fill', 'Remplir les Dimensions'), ('smart', 'Redimensionnement Intelligent'), ('content_aware', 'Redimensionnement Adapté au Contenu')], default='smart', max_length=20),
        ),
        migrations.AddField(
            model_name='compressionstrategy',
            name='responsive_sizes',
            field=models.CharField(default='320,768,1024,1920', help_text='Tailles en pixels pour les images responsives (séparées par des virgules)', max_length=200),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='cache_hit_rate',
            field=models.FloatField(default=0, help_text='Taux de succès du cache (%)'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='dom_interactive_time',
            field=models.FloatField(blank=True, help_text="Temps jusqu'à DOM Interactive (en secondes)", null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='first_byte_time',
            field=models.FloatField(blank=True, help_text='Time to First Byte (TTFB) en secondes', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='perceived_loading_speed',
            field=models.FloatField(blank=True, help_text='Vitesse de chargement perçue (score de 1 à 10)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='psnr_score',
            field=models.FloatField(blank=True, help_text='Peak Signal-to-Noise Ratio', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='size_reduction_percentage',
            field=models.FloatField(default=0, help_text='Pourcentage de réduction de la taille'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='ssim_score',
            field=models.FloatField(blank=True, help_text='Score SSIM (Structural Similarity Index)', null=True),
        ),
        migrations.AlterField(
            model_name='compressionstrategy',
            name='algorithm',
            field=models.CharField(choices=[('intelligent', 'Compression Intelligente'), ('lossy', 'Compression avec Perte Optimisée'), ('lossless', 'Compression sans Perte'), ('adaptive', 'Compression Adaptative'), ('content_aware', 'Compression Adaptée au Contenu')], default='intelligent', max_length=20),
        ),
        migrations.AlterField(
            model_name='compressionstrategy',
            name='output_format',
            field=models.CharField(choices=[('WEBP', 'WebP (Recommandé)'), ('AVIF', 'AVIF (Nouvelle Génération)'), ('JPEG', 'JPEG'), ('PNG', 'PNG')], default='WEBP', max_length=10),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='bandwidth_saved',
            field=models.IntegerField(help_text='Bande passante économisée (en bytes)'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='load_time_optimized',
            field=models.FloatField(help_text="Temps de chargement de l'image optimisée (en secondes)"),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='load_time_original',
            field=models.FloatField(help_text="Temps de chargement de l'image originale (en secondes)"),
        ),
    ]
