# Generated by Django 5.1 on 2024-12-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_alter_performancemetric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
